### PR TITLE
Add automatically updated docs site

### PR DESCRIPTION
**Pull request by krisbitney**
Closes: https://github.com/polywrap/monorepo/issues/702

Adds a docusaurus site with a script that generates documentation for each package in the repo. When a new package is added to the repo, no manual changes need to be made to the docusaurus site. The documentation package just needs to be rebuilt.

This PR depends on https://github.com/polywrap/monorepo/pull/1094

Feedback welcome!

### CODE REVIEW

**Comment by Niraj-Kamdar** [comment]
I'd like to have it with the same hierarchy as we have it in the repo

**Comment by krisbitney** [comment]
> I'd like to have it with the same hierarchy as we have it in the repo

I updated it to keep the same hierarchy. It also now adds in the readmes found in the repo folders.

**Comment by dOrgJelli** [comment]
Hey @krisbitney, since the `docgen` command is still not released, let's wait until that's released before merging this.

**Comment by Niraj-Kamdar** [comment]
@krisbitney Is this ready to merge now?

**Pull request merged**
